### PR TITLE
Multiple new options : @font-face directly in same file, regex in option, local CSS in option (not external file)

### PR DESCRIPTION
**Pull request by KenorFR**
```
new IconFontPlugin({
        iconCssRegex: /content\s*:\s*url\(["']?(.*?\.svg)["']?\);/g,
        output: '../font/',
        fontFaceOutput: false
    });
```

### CODE REVIEW

**Comment by AlfredMou** [comment]
en, we have review this pull request  , and we will add these new options in next version
- property: icon font css property name
- localCSSTemplate: accept css template string ( it's css template file path in this version)
- localCSSTemplatePath: accept css template path
- cssInLine: ture/fase    insert @ font-face into the document by style tag or generate css file
Sorry we can not insert @ font-face into the css file because we have provided feature to insert @ font-face into the document without css file。

**Comment by KenorFR** [comment]
No worries, it's too bad for the @font-face, it seemed to me to be the most important functionality of all. This avoided a manual action.

**Comment by rainfore** [comment]
`localCSSTemplate` and `globalCSSTemplate` make breaking change. We will implement them in next version.

**Comment by rainfore** [comment]
Use this issue to follow up: https://github.com/vusion/icon-font-loader/issues/9

**Pull request closed without merging**
