### PR TITLE
Pass through startCodepoint option to webfontsGenerator

### PR DESCRIPTION
**Pull request by IndianaHorrscht**
For my project we have hardcoded code points in the project CSS. We are migrating to icon-font-loader but in order to keep the same code points I need to be able to send through startCodepoint.

### CODE REVIEW

**Comment by rainfore** [comment]
We have considered about this option. Now it seems to be useful and added in [v1.1.0](https://github.com/vusion/icon-font-loader/releases/tag/v1.1.0)

**Comment by IndianaHorrscht** [comment]
Thank you very much for the quick turnaround!

**Comment by rainfore** [comment]
My pleasure! Could you give a star if you like it?

**Comment by IndianaHorrscht** [comment]
Done :)

**Pull request merged**
